# Travis CI (MIT License) configuration file for WordPress projects.
# @link https://travis-ci.org/

addons:
  ssh_known_hosts: git.wpengine.com

script:
  - bin/test

deploy:
-   provider: script
    script:
    - bin/deploy
    skip_cleanup: true
    on:
      branch: master
-   provider: script
    script:
    - bin/deploystaging
    skip_cleanup: true
    on:
      branch: develop
